### ISSUE TITLE
Implement Timeout Configuration for DAG Tasks

### ISSUE THREAD

**Issue by yohamta** [daguflow/dagu#565]
**Overview**
Add a `timeout` field to the DAG configuration to specify the maximum time allowed for a task.

**Requirements**
When a timeout occurs:

- Mark the entire DAG as errored
- Cancel all steps currently in execution

**Implementation**
- Modify the DAG configuration schema to include the new timeout field
- Update [scheduler](https://github.com/daguflow/dagu/blob/main/internal/dag/scheduler/scheduler.go) logic

**Example DAG configuration**
```
timeout: 3600  # Timeout in seconds (1 hour)
steps:
  - command: some long work
```

**Testing**

- Add unit tests for the timeout functionality
- Create integration tests with DAGs that trigger timeouts
- Ensure proper error handling and logging of timeout events

**Comment by Kiyo510** [comment]
@yohamta 
Hi yohamta.
May I work on this issue?

**Comment by yohamta** [comment]
@Kiyo510 Thank you for your interest! That would be greatly helpful. Please don't hesitate to ask me know if you have any questions or need clarification on anything.
