### ISSUE TITLE
ssh executor does not support login in by passwd,only support secret key

### ISSUE THREAD

**Issue by xicaixiaokeke** [daguflow/dagu#584]
steps:
  - name: step1
    executor:
      type: ssh
      config:
        user: dagu
        ip: XXX.XXX.XXX.XXX
        port: 22
        key: /Users/dagu/.ssh/private.pem
    command: /usr/sbin/ifconfig

**Comment by halalala222** [comment]
@yohamta
hi , can i try to work on this issue ?

**Comment by yohamta** [comment]
Hi @halalala222, thanks for offering to help out! Yes please, that would be extremely helpful if you could take a look at the issue. Appreciate it.

**Comment by halalala222** [comment]
https://github.com/daguflow/dagu/pull/655 in this pr i try to work on this issue

**Comment by xicaixiaokeke** [comment]
thank you. every thing is ok!



---Original---
From: ***@***.***&gt;
Date: Thu, Aug 8, 2024 17:01 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [daguflow/dagu] ssh executor does not support login in bypasswd,only support secret key (Issue #584)




 
#655 in this pr i try to work on this issue

**Comment by yohamta** [comment]
Thank you very much!
